language: cpp
compiler:
  - gcc

addons:
  sonarcloud:
    organization: "juliancamacho341"
    token: ${SONAR_TOKEN}

script:
  - mkdir build
  - cd build
  - cmake ..
  - make ..
  - ./cpp-ci-pipeline
  - cd ..
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

